definitions:
  models.Session:
    properties:
      created_at:
        example: "2025-11-20T10:00:00Z"
        type: string
      finished_at:
        example: "2025-11-20T11:00:00Z"
        type: string
      id:
        type: integer
      started_at:
        example: "2025-11-20T10:00:00Z"
        type: string
      updated_at:
        example: "2025-11-20T10:00:00Z"
        type: string
      workout_id:
        example: 1
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        example: "2025-11-20T10:00:00Z"
        type: string
      email:
        example: mihail.marinescu@example.com
        type: string
      id:
        type: integer
      name:
        example: Mihail
        type: string
      updated_at:
        example: "2025-11-20T10:00:00Z"
        type: string
    type: object
  models.Workout:
    properties:
      created_at:
        example: "2025-11-20T10:00:00Z"
        type: string
      id:
        type: integer
      scheduled:
        example: "2025-11-20T10:00:00Z"
        type: string
      type:
        example: Yoga
        type: string
      updated_at:
        example: "2025-11-20T10:00:00Z"
        type: string
      user_id:
        example: 1
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/sessions:
    post:
      consumes:
      - application/json
      parameters:
      - description: Session
        in: body
        name: session
        required: true
        schema:
          $ref: '#/definitions/models.Session'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Session'
      summary: Create a session
      tags:
      - Sessions
  /api/v1/sessions/{id}:
    get:
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Session'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a session by ID
      tags:
      - Sessions
  /api/v1/users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - Users
  /api/v1/users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user by ID
      tags:
      - Users
  /api/v1/workouts:
    post:
      consumes:
      - application/json
      parameters:
      - description: Workout
        in: body
        name: workout
        required: true
        schema:
          $ref: '#/definitions/models.Workout'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Workout'
      summary: Create a workout
      tags:
      - Workouts
  /api/v1/workouts/{id}:
    get:
      parameters:
      - description: Workout ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Workout'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a workout by ID
      tags:
      - Workouts
swagger: "2.0"
